# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "79f6038c639d31f8da67ad5d6a036fb4"
name = "NS-Retail"
application_url = "https://9113-14-195-73-179.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://9113-14-195-73-179.ngrok-free.app/api/auth" ]

[app_proxy]
url = "https://9113-14-195-73-179.ngrok-free.app"
subpath = "retail-signup"
prefix = "apps"
