// extensions/checkout-ui/src/Checkout.jsx
//
// Processing fee — N% of cart GRAND TOTAL (items + shipping + tax) —
// added at checkout as a real cart line item. Shopify Checkout UI
// extensions cannot increase the cart total directly; the only
// supported path is to add a line item via
// `applyCartLinesChange({type:'addCartLine', ...})` referencing a
// real ProductVariant.
//
// ── Tier-picker pricing model (2026-07-01) ───────────────────────────
//
// Instead of the previous quantity-as-cents trick (single $0.01 variant,
// qty inflated to cents-of-fee → cart displayed weird "× 8985"), we now
// use a PRE-CREATED grid of variants at $0.10 increments from $0.10 to
// $100.00 (1000 variants total, generated by scripts/create-fee-variants.js).
//
// At checkout we compute the desired fee amount, `pickTier` finds the
// closest tier variant, and we add it with quantity always = 1. Cart
// displays cleanly as "Processing Fee — $3.50 × 1".
//
// Trade-off: ±$0.05 precision loss per order (nearest tier). Acceptable
// for a 3% surcharge (~1.5% of a $3 fee) and it eliminates the customer
// confusion caused by the huge qty number.
//
// ── Two compensation layers ──────────────────────────────────────────
//
//  1. Self-compensation (fee-on-fee):
//     realCartTotal = totalAmount − feeLine.cost.totalAmount
//     Prevents the fee from compounding on itself when the cart
//     re-evaluates (the fee line's totalAmount is already inside
//     `cost.totalAmount`).
//
//  2. Discount-on-fee compensation (tier bump):
//     Shopify applies cart-wide / order-wide discounts to EVERY cart
//     line including ours. There is no native "non-discountable" line
//     flag and Discount Functions cannot intercept native code /
//     automatic discounts. So we INFLATE the desired fee (using the
//     detected discount rate) and pick a HIGHER tier so that AFTER
//     Shopify applies the discount to our fee line, the customer's NET
//     fee equals exactly N% of `realCartTotal`.
//
//        discountRateOnFee = (currentTierPrice − feeLine.cost.totalAmount) / currentTierPrice
//        desiredFeeNet     = realCartTotal × N%
//        inflated          = desiredFeeNet ÷ (1 − discountRateOnFee)
//        target            = pickTier(inflated)  ← closest variant
//
//     Converges in 2 iterations: round 1 adds base tier, round 2 sees
//     the actual discount allocation and switches to a higher tier.
//
// ── Setup (per-environment, one-time) ────────────────────────────────
//   1. Create a "Processing Fee" product in the target Shopify store
//      (see scripts/create-fee-variants.js for exact product settings)
//   2. Run:
//        SHOPIFY_SHOP=... SHOPIFY_ADMIN_ACCESS_TOKEN=... \
//        node scripts/create-fee-variants.js gid://shopify/Product/<id>
//   3. Copy the printed `FEE_TIERS = [...]` array
//   4. Paste it below (replacing the empty array)
//   5. shopify app deploy
//
// ── Lifecycle / when the fee appears ─────────────────────────────────
// Cart-line mutations require `instructions.value.lines.canAddCartLine`
// — which Shopify only sets to true AFTER the buyer has entered a
// shipping address. So the fee appears at the shipping step (after
// address, before payment), exactly when "the totals update" — matching
// the operator's intent that the customer sees the true charge before
// picking a payment method.

import '@shopify/ui-extensions/preact'
import { render } from 'preact'
import { useSignalEffect } from '@preact/signals'

// ── HARDCODED — generated by scripts/create-fee-variants.js ─────────
// Paste the script's output over this array. Entries MUST be sorted
// ascending by `price`. Each `gid` is the tier variant's full Shopify
// GID. An empty array is a valid "not yet set up" state — the extension
// safely no-ops and logs a warning.
/** @type {Array<{ price: number, gid: string }>} */
const FEE_TIERS = [
  // { price: 0.10, gid: 'gid://shopify/ProductVariant/REPLACE_ME_10' },
  // { price: 0.20, gid: 'gid://shopify/ProductVariant/REPLACE_ME_20' },
  // ... (paste 1000 entries from fee-tiers.json)
]

// Percentage charged on cart GRAND TOTAL (items + shipping + tax).
// 3 = 3%.
const FEE_PERCENT = 3

// Given a desired fee amount, find the closest tier variant.
// FEE_TIERS is assumed sorted ascending by price. Returns null when the
// tier table is empty (deploy-before-script state). Clamps to first/last
// tier when the amount is outside the covered range.
/**
 * @param {number} desiredAmount
 * @returns {{ price: number, gid: string } | null}
 */
function pickTier(desiredAmount) {
  if (FEE_TIERS.length === 0) return null
  if (desiredAmount <= FEE_TIERS[0].price) return FEE_TIERS[0]
  const last = FEE_TIERS[FEE_TIERS.length - 1]
  if (desiredAmount >= last.price) return last
  let closest = FEE_TIERS[0]
  let minDist = Math.abs(FEE_TIERS[0].price - desiredAmount)
  for (const tier of FEE_TIERS) {
    const dist = Math.abs(tier.price - desiredAmount)
    if (dist < minDist) {
      minDist = dist
      closest = tier
    }
  }
  return closest
}

export default async () => {
  render(<ProcessingFee />, document.body)
}

function ProcessingFee() {
  // eslint-disable-next-line no-console
  console.log(
    `[processing-fee] ⏱️  render · ${FEE_TIERS.length} tier variants loaded`,
  )

  useSignalEffect(() => {
    // Guard: tier table empty (script not yet run for this environment).
    if (FEE_TIERS.length === 0) {
      // eslint-disable-next-line no-console
      console.log(
        '[processing-fee] ⚠️  FEE_TIERS is empty — run scripts/create-fee-variants.js and paste the output into Checkout.jsx, then rebuild.',
      )
      return
    }

    // ── Gate on the buyer-journey + cart-mutation capability ────────
    const canAdd = shopify.instructions.value?.lines?.canAddCartLine
    if (!canAdd) {
      // eslint-disable-next-line no-console
      console.log(
        '[processing-fee] ⏸️  skip — canAddCartLine=false (shipping address not entered yet)',
      )
      return
    }

    // Use GRAND TOTAL (items + shipping + tax). Note: totalAmount
    // ALREADY includes our existing fee line, so we subtract it below
    // in `realCartTotal` to prevent the fee from compounding on itself.
    const totalAmount = Number(shopify.cost.totalAmount.value?.amount) || 0
    if (totalAmount === 0) return

    const feeRate = FEE_PERCENT / 100
    const lines = shopify.lines.value || []

    // Find EVERY cart line whose merchandiseId matches one of our tier
    // variants. Normally there's at most one, but we defensively clean
    // up duplicates (e.g. a stale line from an earlier tier that failed
    // to remove during a switch, or a manually-added variant).
    const knownGids = new Set(FEE_TIERS.map((t) => t.gid))
    const feeLines = lines.filter((l) => knownGids.has(l?.merchandise?.id))
    const existingFeeLine = feeLines[0] || null

    // ── Layer 1 — self-compensation ────────────────────────────────
    const existingFeeDollars = existingFeeLine
      ? Number(existingFeeLine.cost?.totalAmount?.amount) || 0
      : 0
    const realCartTotal = totalAmount - existingFeeDollars

    // ── Layer 2 — discount-on-fee detection ────────────────────────
    // Look up the current tier's pre-discount price from FEE_TIERS
    // (we CAN'T rely on line.cost.subtotalAmount — that field isn't in
    // the Checkout UI CartLineCost surface). Compare against the line's
    // post-discount totalAmount to derive the rate.
    let discountRateOnFee = 0
    if (existingFeeLine) {
      const currentTier = FEE_TIERS.find(
        (t) => t.gid === existingFeeLine.merchandise.id,
      )
      const qty = Number(existingFeeLine.quantity) || 1
      const preDiscountSubtotal = (currentTier?.price || 0) * qty
      if (preDiscountSubtotal > 0) {
        discountRateOnFee =
          (preDiscountSubtotal - existingFeeDollars) / preDiscountSubtotal
      }
    }
    // Cap at [0, 0.95] to defend against divide-by-near-zero on
    // hypothetical 100% discounts.
    const capped = Math.min(Math.max(discountRateOnFee, 0), 0.95)

    // Desired NET fee (customer actually pays post-discount) = 3% of
    // real cart. Inflate to the pre-discount amount we need to bake
    // into the picked tier so that AFTER discount the net matches.
    const desiredNet = realCartTotal * feeRate
    const inflated = desiredNet / (1 - capped)

    const target = pickTier(inflated)
    if (!target) {
      // eslint-disable-next-line no-console
      console.warn('[processing-fee] ⚠️  no matching tier for inflated=' + inflated)
      return
    }

    const existingTierPrice = existingFeeLine
      ? FEE_TIERS.find((t) => t.gid === existingFeeLine.merchandise.id)?.price
      : null

    // eslint-disable-next-line no-console
    console.log(
      `[processing-fee] 💵 totalAmount=$${totalAmount.toFixed(2)} · realCart=$${realCartTotal.toFixed(2)} · discountOnFee=${(capped * 100).toFixed(2)}% · desiredNet=$${desiredNet.toFixed(2)} · inflated=$${inflated.toFixed(2)} · targetTier=$${target.price.toFixed(2)} · existingTier=${existingTierPrice != null ? '$' + existingTierPrice.toFixed(2) : 'none'} · duplicateLines=${Math.max(0, feeLines.length - 1)}`,
    )

    // Cleanup: remove any duplicate fee lines beyond the primary one.
    // Fires FIRST — even before the primary-line branch below — so a
    // stale extra line doesn't stick around across ticks.
    if (feeLines.length > 1) {
      for (const stale of feeLines.slice(1)) {
        // eslint-disable-next-line no-console
        console.log(
          `[processing-fee] 🧹 removing duplicate fee line ${stale.id}`,
        )
        void shopify.applyCartLinesChange({
          type: 'removeCartLine',
          id: stale.id,
          quantity: stale.quantity,
        })
      }
    }

    // Case 1: cart empty / no fee needed → remove any existing.
    if (desiredNet <= 0) {
      if (existingFeeLine) {
        // eslint-disable-next-line no-console
        console.log('[processing-fee] 🗑️  removing fee line (desired=$0)')
        void shopify.applyCartLinesChange({
          type: 'removeCartLine',
          id: existingFeeLine.id,
          quantity: existingFeeLine.quantity,
        })
      }
      return
    }

    // Case 2: no fee line yet → add the target tier.
    if (!existingFeeLine) {
      // eslint-disable-next-line no-console
      console.log(`[processing-fee] ➕ adding tier variant $${target.price.toFixed(2)}`)
      void shopify.applyCartLinesChange({
        type: 'addCartLine',
        merchandiseId: target.gid,
        quantity: 1,
      })
      return
    }

    // Case 3: correct tier already in cart → enforce qty=1 invariant.
    if (existingFeeLine.merchandise.id === target.gid) {
      if (existingFeeLine.quantity !== 1) {
        // eslint-disable-next-line no-console
        console.log(
          `[processing-fee] 🔄 resetting qty ${existingFeeLine.quantity} → 1 on tier $${target.price.toFixed(2)}`,
        )
        void shopify.applyCartLinesChange({
          type: 'updateCartLine',
          id: existingFeeLine.id,
          quantity: 1,
        })
      }
      return
    }

    // Case 4: wrong tier in cart → switch (remove old, then add new).
    // Chain via `.then` so remove completes before add — otherwise
    // Shopify may briefly see both lines and pick the wrong one for
    // discount allocation.
    // eslint-disable-next-line no-console
    console.log(
      `[processing-fee] 🔄 switching tier $${existingTierPrice?.toFixed(2)} → $${target.price.toFixed(2)}`,
    )
    void shopify
      .applyCartLinesChange({
        type: 'removeCartLine',
        id: existingFeeLine.id,
        quantity: existingFeeLine.quantity,
      })
      .then(() =>
        shopify.applyCartLinesChange({
          type: 'addCartLine',
          merchandiseId: target.gid,
          quantity: 1,
        }),
      )
  })

  // Headless behaviour — no visible UI.
  return null
}
