import mongoose from 'mongoose'

// Snapshot of one invoice included in a batch payment.
const invoiceDetailSchema = new mongoose.Schema(
  {
    invoiceId: { type: mongoose.Schema.Types.ObjectId, ref: 'Invoice' },
    shopifyOrderId: String,
    orderName: String,
    qboInvoiceId: String,
    qboDocNumber: String,
    amountDue: Number,
    currency: { type: String, default: 'USD' },
    // Vendor Bill (A/P) state at the moment the batch was created — sourced
    // from the cross-repo two-hop join (dropship_mappings → cdo_orders.retailQbo).
    // The wholesale app READS this; ns-retail owns + writes it. The bill is
    // automatically reconciled (QBO BillPayment created) by the ns-retail
    // processBillReconciliation CRON once this invoice's paymentStatus becomes
    // 'paid' — typically within the next CRON tick (every 6 hours production /
    // 2 minutes testing). No immediate direct write from wholesale is possible
    // since ns-retail owns the cdo_orders collection.
    vendorBillId: String,
    vendorBillDocNumber: String,
    vendorBillAmount: Number,
    vendorBillPaymentStatus: String,
    // Per-invoice result of the batch mark-paid operation
    markResult: { type: String, enum: ['success', 'error', 'skipped'] },
    markError: String,
  },
  { _id: false },
)

const adminOrderBatchSchema = new mongoose.Schema(
  {
    // Unique human-readable batch identifier — e.g. "BATCH-20260625-001".
    // Generated by the service from the current date + an atomic counter.
    batchId: { type: String, required: true, unique: true },
    shop: { type: String, required: true, index: true },

    // Payment reference entered by the admin (cheque number, bank transfer
    // reference, EFT confirmation, etc.).
    referenceNumber: { type: String, required: true },
    // Date the physical payment was made (may differ from processedAt).
    paymentDate: { type: Date, required: true },
    notes: String,

    // Financials — computed at batch creation time from the included invoices.
    totalInvoiceAmount: { type: Number, default: 0 },
    // Vendor bill totals are best-effort: amounts come from the cross-repo
    // join at preview time; they may be null for orders whose retail bill
    // hasn't been created yet.
    totalVendorBillAmount: { type: Number, default: 0 },
    totalBatchAmount: { type: Number, default: 0 },
    orderCount: { type: Number, default: 0 },

    // MongoDB IDs of included invoices — for fast re-query.
    invoiceIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Invoice' }],

    // Full per-invoice detail snapshot for the audit trail and history UI.
    invoiceDetails: [invoiceDetailSchema],

    // Audit fields
    processedBy: String,
    processedAt: { type: Date, default: Date.now },

    // Result summary
    // 'completed'  — every invoice was marked paid without error
    // 'partial'    — some invoices succeeded, some failed
    // 'failed'     — every invoice failed (extremely rare)
    status: {
      type: String,
      enum: ['completed', 'partial', 'failed'],
      default: 'completed',
      index: true,
    },
    successCount: { type: Number, default: 0 },
    errorCount: { type: Number, default: 0 },
    errors: { type: [String], default: [] },
  },
  { collection: 'admin_order_batches', timestamps: true },
)

export default mongoose.models.AdminOrderBatch ||
  mongoose.model('AdminOrderBatch', adminOrderBatchSchema)
